language: node_js
sudo: false
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
os:
  - linux
  - windows
cache: npm
services:
  - mongodb
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install mongodb; fi
