language: node_js
sudo: false
node_js:
- '8'
- '9'
cache:
  directories:
  - node_modules
env:
- CXX=g++-4.8
services:
- mongodb
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
