language: node_js
sudo: false
node_js:
  - 10
  - 12
os:
  - linux
  - windows
cache: npm
services:
  - mongodb
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install mongodb; fi
after_script:
  - curl -s https://codecov.io/bash | bash
